name: Build Vim

on:
  push:
    branches:
      - master
    paths-ignore:
      - vimrev.txt
      - vimver.txt
  pull_request:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (in vim repo) to create a release'
        required: true
        type: string
      base_commit:
        description: 'Base commit or tag in vim-win32-installer repo'
        required: true
        type: string

permissions:
  actions: write # to cancel a workflow run
  contents: read

env:
  VIMREPO: https://github.com/vim/vim
  DEPENDENCIES: 'C:\dependencies'
  GETTEXT_PATH: 'C:\dependencies\msys64\usr\bin'  # msgfmt, etc.
  VCPKG_ROOT: 'C:\vcpkg'

  # Account for committing
  USER_NAME: "github-actions[bot]"
  USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"

  #
  # Interfaces
  #

  # Lua
  LUA_VER_DOT: '5.4'
  LUA_RELEASE: '5.4.8'
  LUA_URL: https://downloads.sourceforge.net/luabinaries/lua-%LUA_RELEASE%_Win%BITS%_dllw6_lib.zip
  LUA_DIR: 'C:\dependencies\Lua'

  # Perl
  PERL_VER_DOT_32: '5.38'
  PERL_RELEASE_32: '5.38.2.1'
  PERL_RELEASE_NODOT_32: '5382'
  PERL_URL_32: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_%PERL_RELEASE_NODOT_32%_%BITS%bit/strawberry-perl-%PERL_RELEASE%-%BITS%bit-portable.zip

  PERL_VER_DOT_64: '5.38'
  PERL_RELEASE_64: '5.38.2.2'
  PERL_URL_64: https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_%PERL_RELEASE_NODOT%_%BITS%bit/strawberry-perl-%PERL_RELEASE%-%BITS%bit-portable.zip
  PERL_DIR: 'C:\dependencies\Strawberry\perl'

  # Python 2
  PYTHON2_VER_DOT: '2.7'
  PYTHON2_RELEASE: '2.7.18'
  PYTHON2_URL_32: https://www.python.org/ftp/python/%PYTHON2_RELEASE%/python-%PYTHON2_RELEASE%.msi
  PYTHON2_URL_64: https://www.python.org/ftp/python/%PYTHON2_RELEASE%/python-%PYTHON2_RELEASE%.amd64.msi
  PYTHON2_DIR: 'C:\dependencies\python2'

  # Python 3
  PYTHON3_VER_DOT: '3.12'
  PYTHON3_RELEASE: '3.12.10'
  PYTHON3_URL: https://www.python.org/ftp/python/%PYTHON3_RELEASE%/python-%PYTHON3_RELEASE%%PYARCH%.exe
  PYTHON3_DIR: 'C:\dependencies\python3'

  # Racket
  RACKET_VER: 3m_dif58g
  RACKET_RELEASE: '8.17'
  RACKET_URL_32: https://users.cs.utah.edu/plt/installers/%RACKET_RELEASE%/racket-minimal-%RACKET_RELEASE%-i386-win32-bc.tgz
  RACKET_URL_64: https://users.cs.utah.edu/plt/installers/%RACKET_RELEASE%/racket-minimal-%RACKET_RELEASE%-x86_64-win32-bc.tgz
  RACKET_DIR: 'C:\dependencies\racket'

  # Ruby
  RUBY_VER_DOT: '3.4'
  RUBY_API_VER_LONG: '3.4.0'
  RUBY_RELEASE: '3.4.9-1'
  RUBY_SRC_URL: https://github.com/ruby/ruby/archive/%RUBY_BRANCH%.zip
  RUBY_URL: https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-%RUBY_RELEASE%/rubyinstaller-%RUBY_RELEASE%-%ARCH%.7z
  RUBY_DIR: 'C:\dependencies\rubyinstaller'

  # TCL
  # Disabled. There are no prebuilt binaries for Windows.

  #
  # Other dependencies
  #

  # gettext
  GETTEXT_VER: '1.0'
  ICONV_VER: '1.19'
  GETTEXT_32_URL: https://github.com/mlocati/gettext-iconv-windows/releases/download/v%GETTEXT_VER%-v%ICONV_VER%/gettext%GETTEXT_VER%-iconv%ICONV_VER%-shared-32.zip
  GETTEXT_64_URL: https://github.com/mlocati/gettext-iconv-windows/releases/download/v%GETTEXT_VER%-v%ICONV_VER%/gettext%GETTEXT_VER%-iconv%ICONV_VER%-shared-64.zip
  #INTL_VCPKG: 'C:\vcpkg\packages\gettext-libintl_arm64-windows'
  #ICONV_VCPKG: 'C:\vcpkg\libiconv_arm64-windows'
  GETTEXT_DIR: 'C:\dependencies\gettext'

  # winpty
  WINPTY_URL: https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msvc2015.zip
  WINPTY_VCPKG: 'C:\vcpkg\packages\winpty_arm64-windows'

  # ShellExecAsUser
  SHELLEXECASUSER_URL: https://nsis.sourceforge.io/mediawiki/images/1/1d/ShellExecAsUserUnicodeUpdate.zip

  # libsodium
  SODIUM_RELEASE: '1.0.22'
  SODIUM_VC_VER: 'v143'
  SODIUM_URL: https://download.libsodium.org/libsodium/releases/libsodium-%SODIUM_RELEASE%-stable-msvc.zip
  SODIUM_DIR: 'C:\dependencies\libsodium'


  # Skip pattern
  # FIXME: Some tests are flaky and often fail.
  TEST_SKIP_PAT: 'Test_terminal_composing_unicode\|Test_terminal_version'
  TEST_SKIP_PAT_ARM64: 'Test_terminal_composing_unicode\|Test_terminal_version\|Test_gui_lowlevel_keyevent\|Test_QWERTY_Ctrl_minus\|Test_mswin_event_character_keys\|Test_mswin_event_function_keys\|Test_mswin_event_movement_keys'

  # Escape sequences
  COL_RED: "\x1b[31m"
  COL_GREEN: "\x1b[32m"
  COL_YELLOW: "\x1b[33m"
  COL_RESET: "\x1b[m"

jobs:
  check-updates:
    runs-on: ubuntu-slim

    # Don't run scheduled workflow on forks.
    if: ${{ github.repository_owner == 'vim' || github.event_name != 'schedule' }}

    outputs:
      continue: ${{ steps.check.outputs.continue }}
      create-release: ${{ steps.check.outputs.create-release }}
      signing: ${{ steps.check.outputs.signing }}

    steps:
    - uses: actions/checkout@v6
      if: github.event_name != 'workflow_dispatch'
    - uses: actions/checkout@v6
      if: github.event_name == 'workflow_dispatch'
      with:
        ref: ${{inputs.base_commit}}

    - name: Checkout Vim
      shell: bash
      run: |
        if ! git clone ${VIMREPO}.git --shallow-exclude="$(cat vimver.txt)"; then
          # No new commits since the version written in vimver.txt.
          if [ "${{ github.event_name }}" = 'pull_request' ]; then
            git clone ${VIMREPO}.git --depth=5
          else
            exit 0
          fi
        fi
        if [ "${{github.event_name}}" = 'workflow_dispatch' ]; then
          git -C vim checkout "${{inputs.tag}}"
        fi
        git -C vim log -4 --color=always

    - name: Get changelog
      id: changelog
      shell: bash
      run: |
        mkdir -p package/artifacts/info
        if [ ! -d vim ]; then
          # No new commits.
          exit 0
        fi

        cd vim
        git rev-parse HEAD > ../package/artifacts/info/latestrev.txt
        if [ "$(git tag)" = "" ]; then
          # No new tags.
          cp ../vimver.txt ../package/artifacts/info/latesttag.txt
          exit 0
        fi

        latesttag=$(git describe --tags --abbrev=0)
        echo $latesttag > ../package/artifacts/info/latesttag.txt
        echo $latesttag > ../vimver.txt
        oldrev=$(cat ../vimrev.txt)
        if git log --format='format:' $oldrev > /dev/null 2>&1; then
          logopt=$oldrev..HEAD
        else
          logopt=--
        fi
        commiturl=${VIMREPO}/commit/
        echo "ChangeLog in Markdown:"
        git log --format='format:%H %s' $logopt | \
          sed -e 's/[][_*^<`\\]/\\&/g' \
              -e "s#^\([0-9a-f]*\) patch \([0-9.a-z]*\)#* [\2]($commiturl\1)#" \
              -e "s#^\([0-9a-f]*\) \(.*\)#* [\2]($commiturl\1)#" | \
          tee ../package/artifacts/info/changelog.md
        echo
        echo "ChangeLog in text:"
        git log --format='format:* %s' $logopt | \
          sed -e 's/^\* patch /* /g' | \
          tee ../package/artifacts/info/changelog.txt

    - name: Check changes
      id: check
      shell: bash
      env:
        SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
      run: |
        if git diff --exit-code HEAD vimver.txt; then
          # No updates found.
          echo ${COL_YELLOW}No updates.${COL_RESET}
          if [ "${{ github.event_name }}" = 'pull_request' ]; then
            # Don't skip on pull_request even if there are no updates.
            echo "continue=yes" >> $GITHUB_OUTPUT
            echo "create-release=no" >> $GITHUB_OUTPUT
          else
            # No updates. Cancel the workflow.
            echo "continue=no" >> $GITHUB_OUTPUT
            echo "create-release=no" >> $GITHUB_OUTPUT
            exit 0
          fi
        else
          # Updates found
          if { [ "${{ github.ref_name }}" = 'master' ] || [ "${{github.event_name}}" = 'workflow_dispatch' ]; } \
              && [ "${{ github.repository_owner }}" = 'vim' ]; then
            echo "continue=yes" >> $GITHUB_OUTPUT
            echo "create-release=yes" >> $GITHUB_OUTPUT
          else
            echo "continue=yes" >> $GITHUB_OUTPUT
            echo "create-release=no" >> $GITHUB_OUTPUT
          fi
        fi

        if [ "${{ github.repository }}" = "vim/vim-win32-installer" ] \
           && [ -n "${SIGNPATH_API_TOKEN}" ]; then
          echo "signing=yes" >> $GITHUB_OUTPUT
        else
          echo "signing=no" >> $GITHUB_OUTPUT
        fi

    - name: Upload repository information
      uses: actions/upload-artifact@v7
      with:
        name: repo-info
        path: ./package/artifacts/info


  build:
    needs: [check-updates]
    runs-on: ${{ matrix.os }}
    if: needs.check-updates.outputs.continue == 'yes'

    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86, arm64]
        include:
          - arch: x64
            vcarch: amd64
            warch: x64
            sodiumarch: x64
            bits: 64
            #cygreg: registry
            #pyreg: ""
            sys: mingw64
            os: windows-latest
          - arch: x86
            vcarch: x86
            warch: ia32
            sodiumarch: Win32
            bits: 32
            #cygreg: registry32
            #pyreg: "-32"
            sys: mingw32
            os: windows-latest
          - arch: arm64
            vcarch: arm64
            warch: ''
            sodiumarch: ARM64
            bits: 64
            #cygreg: registry
            #pyreg: ""
            sys: clangarm64
            os: windows-11-arm

    steps:
    - name: Initialize
      id: init
      shell: bash
      run: |
        echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        git config --global core.autocrlf input

        # Lua
        echo "LUA_VER=${LUA_VER_DOT//./}" >> $GITHUB_ENV

        # Perl
        perl_release=${PERL_RELEASE_${{ matrix.bits }}}
        echo "PERL_VER=${PERL_VER_DOT_${{ matrix.bits }}//./}" >> $GITHUB_ENV
        echo "PERL_RELEASE=${perl_release}" >> $GITHUB_ENV
        echo "PERL_RELEASE_NODOT=${perl_release//./}" >> $GITHUB_ENV
        echo "PERL_URL=${PERL_URL_${{ matrix.bits }}}" >> $GITHUB_ENV

        # Python 2
        echo "PYTHON2_VER=${PYTHON2_VER_DOT//./}" >> $GITHUB_ENV
        echo "PYTHON2_URL=${PYTHON2_URL_${{ matrix.bits }}}" >> $GITHUB_ENV

        # Python 3
        echo "PYTHON3_VER=${PYTHON3_VER_DOT//./}" >> $GITHUB_ENV
        #python3_dir=$(cat "/proc/${{ matrix.cygreg }}/HKEY_LOCAL_MACHINE/SOFTWARE/Python/PythonCore/${PYTHON3_VER_DOT}${{ matrix.pyreg }}/InstallPath/@")
        #echo "PYTHON3_DIR=$python3_dir" >> $GITHUB_ENV

        # Racket
        echo "RACKET_URL=${RACKET_URL_${{ matrix.bits }}}" >> $GITHUB_ENV
        echo "MZSCHEME_VER=${RACKET_VER}" >> $GITHUB_ENV

        # Ruby
        echo "RUBY_VER=${RUBY_VER_DOT//./}" >> $GITHUB_ENV
        echo "RUBY_BRANCH=ruby_${RUBY_VER_DOT//./_}" >> $GITHUB_ENV

        # TCL

#    - name: Enable 8.3 names for testing
#      shell: cmd
#      run: |
#        fsutil 8dot3name set D: 0

    - uses: actions/checkout@v6
      if: github.event_name != 'workflow_dispatch'
    - uses: actions/checkout@v6
      if: github.event_name == 'workflow_dispatch'
      with:
        ref: ${{inputs.base_commit}}

    - name: Download repository information
      uses: actions/download-artifact@v8
      with:
        name: repo-info
        path: repo-info

    - name: Checkout Vim
      shell: bash
      run: |
        if ! git clone ${VIMREPO}.git --shallow-exclude="$(cat vimver.txt)"; then
          # No new commits since the version written in vimver.txt.
          if [ "${{ github.event_name }}" = 'pull_request' ]; then
            git clone ${VIMREPO}.git --depth=5
          fi
        fi
        git -C vim checkout "$(cat repo-info/latestrev.txt)"

    - name: Apply experimental patches
      shell: bash
      run: |
        cd vim
        for i in ../patch/*.patch; do
          if [[ $i =~ \*.patch ]]; then
            break
          fi
          git apply -v "$i"
        done

    - uses: msys2/setup-msys2@v2
      with:
        update: false
        location: ${{ env.DEPENDENCIES }}
        msystem: ${{ matrix.sys }}
        #install: gettext
        #pacboy: libiconv:p gettext-runtime:p

    - name: Update msys2 (1st)
      shell: cmd
      run: |
        rem https://www.msys2.org/docs/updating/#potential-issues
        rem pacman-key --refresh-keys
        (
          rem Reset sync databases in case of a corrupted cached state
          echo rm -f /var/lib/pacman/sync/*.db /var/lib/pacman/sync/*.db.sig
          echo pacman --noconfirm -Sy msys2-keyring
          echo pacman --noconfirm -Suuy
        ) > update-msys2.sh

        cmd /c msys2 update-msys2.sh
        del update-msys2.sh

        rem Ignore error when updating the core packages. (All the msys2 processes are terminated.)
        exit 0

    - name: Update msys2 (2nd)
      shell: msys2 {0}
      run: |
        pacman --noconfirm -Suuy
        pacman --noconfirm -S --needed gettext pactoys
        pacboy --noconfirm -S libiconv:p gettext-runtime:p

#    # See: https://github.com/nelsonjchen/reverse-rdp-windows-github-actions
#    # To check the endpoint: ngrok dashboard > Universal Gateway > Endpoints
#    - name: Enable RDP
#      env:
#        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
#      run: |
#        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
#        Expand-Archive ngrok.zip
#        .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
#        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
#        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
#        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
#        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
#        Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp 3389"

    - name: Create a list of download URLs
      shell: cmd
      run: |
        (
          echo %LUA_RELEASE%
          echo %PERL_RELEASE%
          echo %PYTHON3_RELEASE%
          if NOT "${{ matrix.arch }}"=="arm64" (
            echo %PYTHON2_RELEASE%
            echo %RACKET_RELEASE%
            echo %RUBY_RELEASE%
            echo %GETTEXT_32_URL%
            echo %GETTEXT_64_URL%
            echo %WINPTY_URL%
          )
          echo %SODIUM_RELEASE%
        ) > urls.txt

    - name: Cache downloaded files
      uses: actions/cache@v5
      with:
        path: |
          ${{ env.VCPKG_ROOT }}
          downloads
        key: ${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('urls.txt') }}

    - name: Download dependencies
      shell: cmd
      run: |
        path C:\Program Files\7-Zip;%path%
        set BITS=${{ matrix.bits }}
        set ARCH=${{ matrix.arch }}
        if ${{ matrix.vcarch }}==x86 (
          set PYARCH=
        ) else (
          set PYARCH=-${{ matrix.vcarch }}
        )
        if not exist %DEPENDENCIES% md %DEPENDENCIES%

        echo %COL_GREEN%Download Lua%COL_RESET%
        call :downloadfile %LUA_URL% downloads\lua.zip
        7z x downloads\lua.zip -o%LUA_DIR% > nul || exit 1

        echo %COL_GREEN%Download Perl%COL_RESET%
        call :downloadfile %PERL_URL% downloads\perl.zip
        :: Extract only the "perl" folder.
        7z x downloads\perl.zip perl -o%PERL_DIR%\.. > nul || exit 1

        echo %COL_GREEN%Download Python2%COL_RESET%
        call :downloadfile %PYTHON2_URL% downloads\python2.msi
        start "" /wait downloads\python2.msi ^
          /qn TARGETDIR=%PYTHON2_DIR% ADDLOCAL=DefaultFeature,PrependPath

        echo %COL_GREEN%Download Python3%COL_RESET%
        call :downloadfile %PYTHON3_URL% downloads\python3.exe
        start /wait downloads\python3.exe /quiet TargetDir=%PYTHON3_DIR% Include_pip=0 Include_tcltk=0 Include_test=0 Include_tools=0 AssociateFiles=0 Shortcuts=0 Include_doc=0 Include_launcher=0 InstallLauncherAllUsers=0
        copy /Y %PYTHON3_DIR%\python.exe %PYTHON3_DIR%\python3.exe

        if "${{ matrix.arch }}"=="arm64" (
          echo %COL_YELLOW%Skip downloading Racket%COL_RESET%
        ) else (
          echo %COL_GREEN%Download Racket%COL_RESET%
          call :downloadfile %RACKET_URL% downloads\racket-%BITS%.tgz
          7z.exe x -tgzip -so downloads\racket-%BITS%.tgz | 7z.exe x -y -aoa -si -ttar ^
            -o%RACKET_DIR%\..
          type NUL > %RACKET_DIR%\include\bc_suffix.h

          rem Install additional packages for Racket
          %RACKET_DIR%\raco.exe pkg install -i --auto r5rs-lib
        )

        if "${{ matrix.arch }}"=="arm64" (
          echo %COL_YELLOW%Skip downloading Ruby%COL_RESET%
        ) else (
          echo %COL_GREEN%Download Ruby%COL_RESET%
          call :downloadfile %RUBY_URL% downloads\ruby.7z
          7z x downloads\ruby.7z -o%RUBY_DIR%\.. > nul || exit 1
          move %RUBY_DIR%\..\rubyinstaller-%RUBY_RELEASE%-${{ matrix.arch }} %RUBY_DIR% > nul || exit 1

          echo %COL_GREEN%Download Ruby source%COL_RESET%
          call :downloadfile %RUBY_SRC_URL% downloads\ruby_src.zip
          rem Extract the files only we needed to reduce the building time.
          7z x downloads\ruby_src.zip */bin */common.mk */enc/Makefile.in */include */spec/ruby/optional/capi/ext/*_spec.c */version.h */win32 -xr!README.* -xr!*/win32/*.c -xr!*/win32/*.h -o.. > nul || exit 1
          move ..\ruby-%RUBY_BRANCH% ..\ruby > nul || exit 1
        )

        if "${{ matrix.arch }}"=="arm64" (
          echo %COL_GREEN%Prepare gettext%COL_RESET%
          md %GETTEXT_DIR%
          md %GETTEXT_DIR%64
          copy /Y %DEPENDENCIES%\msys64\${{ matrix.sys }}\bin\libiconv-2.dll %GETTEXT_DIR% || exit 1
          copy /Y %DEPENDENCIES%\msys64\${{ matrix.sys }}\bin\libintl-8.dll %GETTEXT_DIR% || exit 1
          copy /Y %GETTEXT_DIR%\libiconv-2.dll %GETTEXT_DIR%64 || exit 1
          copy /Y %GETTEXT_DIR%\libintl-8.dll %GETTEXT_DIR%64 || exit 1
          rem Work around for nsis installer
          rem md %GETTEXT_DIR%32
          rem copy /Y %GETTEXT_DIR%\libiconv-2.dll %GETTEXT_DIR%32 || exit 1
          rem copy /Y %GETTEXT_DIR%\libintl-8.dll %GETTEXT_DIR%32 || exit 1
        ) else (
          echo %COL_GREEN%Download gettext%COL_RESET%
          call :downloadfile %GETTEXT_32_URL% downloads\gettext32.zip
          rem Extract without directories
          7z e -y downloads\gettext32.zip -o%GETTEXT_DIR%32 > nul || exit 1
          call :downloadfile %GETTEXT_64_URL% downloads\gettext64.zip
          rem Extract without directories
          7z e -y downloads\gettext64.zip -o%GETTEXT_DIR%64 > nul || exit 1
          md %GETTEXT_DIR%
          copy /Y %GETTEXT_DIR%%BITS%\libiconv-2.dll %GETTEXT_DIR% || exit 1
          copy /Y %GETTEXT_DIR%%BITS%\libintl-8.dll %GETTEXT_DIR% || exit 1
          if exist %GETTEXT_DIR%%BITS%\libgcc_s_sjlj-1.dll copy %GETTEXT_DIR%%BITS%\libgcc_s_sjlj-1.dll %GETTEXT_DIR% || exit 1
        )

        echo %COL_GREEN%Download winpty%COL_RESET%
        if "${{ matrix.arch }}"=="arm64" (
          call :vcpkg winpty
          copy /Y %WINPTY_VCPKG%\bin\winpty.dll                 vim\src\winpty${{ matrix.bits }}.dll
          copy /Y %WINPTY_VCPKG%\tools\winpty\winpty-agent.exe  vim\src\
        ) else (
          call :downloadfile %WINPTY_URL% downloads\winpty.zip
          7z x -y downloads\winpty.zip -o%DEPENDENCIES%\winpty > nul || exit 1
          copy /Y %DEPENDENCIES%\winpty\${{ matrix.warch }}\bin\winpty.dll        vim\src\winpty${{ matrix.bits }}.dll
          copy /Y %DEPENDENCIES%\winpty\${{ matrix.warch }}\bin\winpty-agent.exe  vim\src\
        )

        echo %COL_GREEN%Download ShellExecAsUser%COL_RESET%
        call :downloadfile "%SHELLEXECASUSER_URL%" downloads\shellexecasuser.zip
        7z.exe x -y downloads\shellexecasuser.zip -o%DEPENDENCIES%\shellexecasuser > nul || exit 1
        mkdir "%ProgramFiles(x86)%\NSIS\Plugins\x86-unicode"
        copy /Y "%DEPENDENCIES%\shellexecasuser\unicode\ShellExecAsUser.dll" ^
          "%ProgramFiles(x86)%\NSIS\Plugins\x86-unicode\ShellExecAsUser.dll" || exit 1

        echo %COL_GREEN%Download libsodium%COL_RESET%
        call :downloadfile %SODIUM_URL% downloads\libsodium.zip -z
        7z x -y downloads\libsodium.zip -o%SODIUM_DIR%\.. > nul || exit 1
        copy /Y %SODIUM_DIR%\${{ matrix.sodiumarch }}\Release\%SODIUM_VC_VER%\dynamic\libsodium.dll  vim\src\

        goto :eof

        :downloadfile
        :: call :downloadfile <URL> <localfile> [-z]
        echo Downloading: %1
        if "%3"=="-z" (
          rem Compare the timestamp
          curl --fail -L -R --retry 2 --retry-delay 5 --retry-all-errors %1 -o %2 -z %2 || exit 1
        ) else if not exist %2 (
          curl --fail -L -R --retry 2 --retry-delay 5 --retry-all-errors %1 -o %2 || exit 1
        )
        goto :eof

        :vcpkg
        :: call :vcpkg package
        vcpkg --vcpkg-root="%VCPKG_ROOT%" install %1:arm64-windows || exit 1
        goto :eof

    - name: Create Ruby's config.h
      if: matrix.arch != 'arm64'
      shell: cmd
      run: |
        call vim\src\msvc-latest ${{ matrix.vcarch }}
        cd ..\ruby
        call win32\configure.bat
        nmake -nologo .config.h.time || exit 1
        xcopy /s .ext\include %RUBY_DIR%\include\ruby-%RUBY_API_VER_LONG%

    - name: Update patchlevel
      id: patchlevel
      shell: bash
      run: |
        cd vim/src
        patchlevel=$(sed -n -e '/included_patches/{n;n;n;s/ *\([0-9]*\).*/\1/p;q}' version.c)
        sed -i -e "s/^\(# define VIM_VERSION_PATCHLEVEL\s\+\).*/\1$patchlevel/" version.h

        # Set MAJOR, MINOR, PATCHLEVEL, PATCHLEVEL_PADDED
        major=$(grep -o -P '#define VIM_VERSION_MAJOR\s+\K[0-9]+' version.h)
        minor=$(grep -o -P '#define VIM_VERSION_MINOR\s+\K[0-9]+' version.h)
        echo "MAJOR=${major}" >> $GITHUB_ENV
        echo "MINOR=${minor}" >> $GITHUB_ENV
        echo "PATCHLEVEL=${patchlevel}" >> $GITHUB_ENV
        patchlevel_padded=$(printf '%04d' ${patchlevel})
        echo "PATCHLEVEL_PADDED=${patchlevel_padded}" >> $GITHUB_ENV

        echo "ver=${major}.${minor}.${patchlevel_padded}" >> $GITHUB_OUTPUT

    - name: Copy src directory to src2
      shell: cmd
      run: |
        cd vim
        xcopy src src2\ /E > nul

    - name: Build
      shell: cmd
      run: |
        call vim\src\msvc-latest ${{ matrix.vcarch }}
        cd vim\src

        :: Create config
        if not exist auto\nmake mkdir auto\nmake
        copy /Y ..\..\vimdll-huge.cfg auto\nmake\
        (
          echo "PERL_VER=%PERL_VER%"
          echo "PERL=%PERL_DIR%"
          echo "PYTHON3_VER=%PYTHON3_VER%"
          echo "PYTHON3=%PYTHON3_DIR%"
          echo "LUA_VER=%LUA_VER%"
          echo "LUA=%LUA_DIR%"
          rem Not supported for ARM64
          if NOT "${{ matrix.arch }}"=="arm64" (
            echo "PYTHON=%PYTHON2_DIR%"
            echo "PYTHON_VER=%PYTHON2_VER%"
            echo "RUBY_VER=%RUBY_VER%"
            echo "RUBY_API_VER_LONG=%RUBY_API_VER_LONG%"
            echo "RUBY=%RUBY_DIR%"
            echo "MZSCHEME_VER=%MZSCHEME_VER%"
            echo "MZSCHEME=%RACKET_DIR%"
          )
          echo "SODIUM=%SODIUM_DIR%"
        ) >> auto\nmake\vimdll-huge.cfg

        rem Build gvim/vim with VIMDLL
        nmake -nologo -f Make_mvc.mak @auto\nmake\vimdll-huge.cfg || exit 1
        if not exist vim${{ matrix.bits }}.dll (
          echo %COL_RED%Build failure.%COL_RESET%
          exit 1
        )
        cd po
        nmake -nologo -f Make_mvc.mak || exit 1
        nmake -nologo -f Make_mvc.mak install-all

    - name: Check version
      shell: cmd
      run: |
        path %LUA_DIR%;%PERL_DIR%\bin;%PYTHON3_DIR%;%PYTHON2_DIR%;%RUBY_DIR%\bin;%RUBY_DIR%\bin\ruby_builtin_dlls;%GETTEXT_DIR%;%RACKET_DIR%;%RACKET_DIR%\lib;%path%
        set "PLTCOLLECTS=%RACKET_DIR%\collects"
        set "PLTCONFIGDIR=%RACKET_DIR%\etc"
        cd vim\src
        start "" /wait .\gvim -silent -register
        echo.
        echo %COL_GREEN%gvim version:%COL_RESET%
        start /wait .\gvim -u NONE -c "redir @a | ver | put a | 1,3d | wq!" ver.txt
        type ver.txt || exit 1
        start /wait .\gvim -u NONE -S ..\..\scripts\if_ver.vim -c quit
        type if_ver.txt
        echo %COL_GREEN%vim version:%COL_RESET%
        .\vim --version || exit 1
        .\vim --not-a-term -u NONE -S ..\..\scripts\if_ver.vim -c quit
        type if_ver.txt

    - name: Build GvimExt
      shell: cmd
      run: |
        mkdir vim\runtime\GvimExt64

        if "${{ matrix.arch }}"=="arm64" (
          call vim\src\msvc-latest ${{ matrix.vcarch }}
          pushd vim\src\GvimExt
          nmake.exe -nologo -f Make_mvc.mak CPU=ARM64 clean all || exit 1
          popd
          robocopy vim\src\GvimExt vim\runtime\GvimExt64 ^
            gvimext.dll gvimext.inf gvimext.reg README.txt /E /NP /NFL /NDL
          if ERRORLEVEL 8 exit 1
          copy /Y vim\src\GvimExt\gvimext.dll vim\src\GvimExt\gvimext64.dll || exit 1
        ) else (
          rem Build both 64- and 32-bit versions of gvimext.dll for the installer

          rem x64
          cmd /C "vim\src\msvc-latest x64 && cd vim\src\GvimExt && nmake.exe -nologo -f Make_mvc.mak CPU=AMD64 clean all"
          robocopy vim\src\GvimExt vim\runtime\GvimExt64 ^
            gvimext.dll gvimext.inf gvimext.reg README.txt /E /NP /NFL /NDL
          if ERRORLEVEL 8 exit 1
          copy /Y vim\src\GvimExt\gvimext.dll vim\src\GvimExt\gvimext64.dll || exit 1

          rem x86
          mkdir vim\runtime\GvimExt32
          cmd /C "vim\src\msvc-latest x86 && cd vim\src\GvimExt && nmake.exe -nologo -f Make_mvc.mak CPU=i386 clean all"
          robocopy vim\src\GvimExt vim\runtime\GvimExt32 ^
            gvimext.dll gvimext.inf gvimext.reg README.txt /E /NP /NFL /NDL
          if ERRORLEVEL 8 exit 1
        )
        rem robocopy returns a non-zero error code even on success.
        exit 0

#    - name: Wait for RDP
#      shell: cmd
#      run: |
#        ping -n 3600 localhost>nul

    - name: Test gvim/vim and show the result of gvim tests
      shell: cmd
      timeout-minutes: 20
      run: |
        path %LUA_DIR%;%PERL_DIR%\bin;%PYTHON3_DIR%;%PYTHON2_DIR%;%RUBY_DIR%\bin;%RUBY_DIR%\bin\ruby_builtin_dlls;%GETTEXT_DIR%;%RACKET_DIR%;%RACKET_DIR%\lib;%path%
        set "PLTCOLLECTS=%RACKET_DIR%\collects"
        set "PLTCONFIGDIR=%RACKET_DIR%\etc"

        if "${{ matrix.arch }}"=="arm64" (
          set "TEST_SKIP_PAT=%TEST_SKIP_PAT_ARM64%"
        )

        call vim\src\msvc-latest ${{ matrix.vcarch }}
        cd vim

        echo %COL_GREEN%Start testing vim in background.%COL_RESET%
        start cmd /c "cd src2\testdir & nmake -nologo -f Make_mvc.mak VIMPROG=..\..\src\vim > nul & echo done>done.txt"

        echo %COL_GREEN%Test gvim:%COL_RESET%
        cd src\testdir
        nmake -nologo -f Make_mvc.mak VIMPROG=..\gvim || exit 1
        cd ..

    - name: Show the result of vim tests
      shell: cmd
      timeout-minutes: 10
      run: |
        path %LUA_DIR%;%PERL_DIR%\bin;%PYTHON3_DIR%;%PYTHON2_DIR%;%RUBY_DIR%\bin;%RUBY_DIR%\bin\ruby_builtin_dlls;%GETTEXT_DIR%;%RACKET_DIR%;%RACKET_DIR%\lib;%path%
        set "PLTCOLLECTS=%RACKET_DIR%\collects"
        set "PLTCONFIGDIR=%RACKET_DIR%\etc"
        call vim\src\msvc-latest ${{ matrix.vcarch }}
        echo %COL_GREEN%Wait for vim tests to finish.%COL_RESET%
        cd vim\src2\testdir
        :: Wait about 10 minutes.
        for /L %%i in (1,1,60) do (
          if exist done.txt goto exitloop
          ping -n 11 localhost > nul
        )
        set timeout=1
        :exitloop

        echo %COL_GREEN%Test results of vim:%COL_RESET%
        if exist messages type messages
        nmake -nologo -f Make_mvc.mak report VIMPROG=..\..\src\vim || exit 1
        if "%timeout%"=="1" (
          echo %COL_RED%Timed out.%COL_RESET%
          exit 1
        )

    - name: Package (zip)
      shell: cmd
      run: |
        call vim\src\msvc-latest ${{ matrix.vcarch }}

        cd package

        set VIM_DIR=vim%MAJOR%%MINOR%
        set PKG=vim-package-${{ matrix.arch }}
        set DEST=%PKG%\vim\%VIM_DIR%
        echo VIM_DIR=%VIM_DIR%>> %GITHUB_ENV%
        echo PKG=%PKG%>> %GITHUB_ENV%

        md %DEST%

        robocopy ..\vim\runtime %DEST% /E /NP /NFL /NDL
        if ERRORLEVEL 8 exit 1
        copy ..\vim\src\*.pdb     . || exit 1
        copy ..\vim\src\*vim*.exe %DEST% || exit 1
        copy ..\vim\src\vim*.dll  %DEST% || exit 1
        copy ..\vim\src\tee\*.exe %DEST% || exit 1
        copy ..\vim\src\xxd\*.exe %DEST% || exit 1
        copy ..\vim\src\libsodium.dll %DEST% || exit 1
        copy ..\vim\src\winpty*   %DEST% || exit 1
        copy ..\vim\README.txt    %DEST% || exit 1
        copy ..\vim\LICENSE       %DEST%\LICENSE.txt || exit 1
        copy ..\vim\uninstall.txt %DEST% || exit 1
        copy ..\vim\vimtutor.bat  %DEST% || exit 1
        copy ..\vim\src\vim.ico   %DEST% || exit 1
        copy ..\vim\src\install.exe %DEST% || exit 1
        copy ..\vim\src\uninstall.exe %DEST% || exit 1
        copy ..\diff.exe          %DEST% || exit 1
        rem copy %LUA_DIR%\lua*.dll   %DEST% || exit 1

        copy %GETTEXT_DIR%\libiconv-2.dll %DEST% || exit 1
        copy %GETTEXT_DIR%\libintl-8.dll  %DEST% || exit 1
        :: Check if libgcc_s_*.dll is required
        set INCLUDE_LIBGCC=0
        if NOT "${{ matrix.arch }}"=="arm64" (
          dumpbin /DEPENDENTS %GETTEXT_DIR%32\libintl-8.dll | findstr /R "libgcc_s_.*\.dll" && set INCLUDE_LIBGCC=1
        )
        if "${{ matrix.arch }}"=="x86" (
          if "%INCLUDE_LIBGCC%" EQU 1 (
            if exist %GETTEXT_DIR%\libgcc_s_sjlj-1.dll copy %GETTEXT_DIR%\libgcc_s_sjlj-1.dll %DEST% || exit 1
          )
        )
        copy %GETTEXT_DIR%64\libiconv-2.dll %DEST%\GvimExt64 || exit 1
        copy %GETTEXT_DIR%64\libintl-8.dll  %DEST%\GvimExt64 || exit 1
        if NOT "${{ matrix.arch }}"=="arm64" (
          copy %GETTEXT_DIR%32\libiconv-2.dll %DEST%\GvimExt32 || exit 1
          copy %GETTEXT_DIR%32\libintl-8.dll  %DEST%\GvimExt32 || exit 1
          if "%INCLUDE_LIBGCC%" EQU 1 (
            if exist %GETTEXT_DIR%32\libgcc_s_sjlj-1.dll copy %GETTEXT_DIR%32\libgcc_s_sjlj-1.dll %DEST% || exit 1
          )
        )
        rem Parentheses are required. Otherwise the number is interpreted as a file descriptor.
        (echo INCLUDE_LIBGCC=%INCLUDE_LIBGCC%)>> %GITHUB_ENV%

        md artifacts\files
        set BASENAME=gvim_${{ steps.patchlevel.outputs.ver }}_${{ matrix.arch }}
        cd %PKG%
        7z a -mx=9 -xr@..\..\exclist.txt ..\artifacts\files\%BASENAME%.zip vim || exit 1
        cd ..
        7z a -mx=9 artifacts\files\%BASENAME%_pdb.7z *.pdb || exit 1

    - name: Package (installer)
      shell: cmd
      run: |
        call vim\src\msvc-latest ${{ matrix.vcarch }}

        if NOT "${{ matrix.arch }}"=="arm64" (
          winget upgrade --disable-interactivity --accept-source-agreements
          winget install -e --id NSIS.NSIS --disable-interactivity --accept-package-agreements
        )

        rem Install ShellExecAsUser
        7z.exe x -y downloads\shellexecasuser.zip -o%DEPENDENCIES%\shellexecasuser > nul || exit 1
        copy /y "%DEPENDENCIES%\shellexecasuser\unicode\ShellExecAsUser.dll" ^
          "%ProgramFiles(x86)%\NSIS\Plugins\x86-unicode\ShellExecAsUser.dll"

        set INST=vim-installer-${{ matrix.arch }}
        set DEST_INST=%INST%\vim\%VIM_DIR%
        robocopy package\%PKG% package\%INST% /E /NP /NFL /NDL
        if ERRORLEVEL 8 exit 1
        robocopy vim\src\GvimExt package\%DEST_INST%\GvimExt /E /NP /NFL /NDL
        if ERRORLEVEL 8 exit 1

        cd vim\nsis

        set WIN64=0
        set ARM64=0

        if "${{ matrix.arch }}"=="x64" set WIN64=1
        if "${{ matrix.arch }}"=="arm64" set ARM64=1

        set BASENAME=gvim_${{ steps.patchlevel.outputs.ver }}_${{ matrix.arch }}
        nmake.exe -nologo -f Make_mvc.mak ^
          "X=OutFile ..\..\package\artifacts\files\%BASENAME%.exe" ^
          "SRC=..\..\package\%DEST_INST%" "VIMTOOLS=..\..\package\%DEST_INST%" ^
          "VIMSRC=..\..\package\%DEST_INST%" "VIMRT=..\..\package\%DEST_INST%" ^
          "GETTEXT=%DEPENDENCIES%" "INCLUDE_LIBGCC=%INCLUDE_LIBGCC%" ^
          "WIN64=%WIN64%" "ARM64=%ARM64%" || exit 1

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: vim-package-${{ matrix.arch }}
        path: ./package/artifacts/files


  release:
    runs-on: ubuntu-slim
    needs: [check-updates, build]
    if: needs.check-updates.outputs.create-release == 'yes'

    permissions:
      id-token: write # needed for attestation
      attestations: write
      artifact-metadata: write
      contents: write # to create release

    steps:
    #- name: Generate token
    #  id: app-token
    #  uses: actions/create-github-app-token@v3
    #  with:
    #    client-id: ${{ secrets.VIM_WIN32_INSTALLER_RELEASE_BOT_CLIENT_ID }}
    #    private-key: ${{ secrets.VIM_WIN32_INSTALLER_RELEASE_BOT_PRIVATE_KEY }}

    - uses: actions/checkout@v6
      if: github.event_name != 'workflow_dispatch'
      with:
        ssh-key: ${{ secrets.VIM_WIN32_INSTALLER_DEPLOY_KEY }}
        #token: ${{ steps.app-token.outputs.token }}
    - uses: actions/checkout@v6
      if: github.event_name == 'workflow_dispatch'
      with:
        ref: ${{inputs.base_commit}}
        ssh-key: ${{ secrets.VIM_WIN32_INSTALLER_DEPLOY_KEY }}
        #token: ${{ steps.app-token.outputs.token }}

    - name: Download all artifacts
      uses: actions/download-artifact@v8

    - name: Attest
      uses: actions/attest@v4
      with:
        subject-path: ./vim-package-*/gvim_*

    - name: Copy files for code signing
      if: needs.check-updates.outputs.signing == 'yes'
      shell: bash
      run: |
        mkdir -p package/artifacts/files
        # Copy all the required files to a single directory
        cp vim-package-*/gvim_*.{exe,zip} package/artifacts/files

    - name: Upload Artifact (for code signing)
      if: needs.check-updates.outputs.signing == 'yes'
      id: upload-unsigned-zip
      uses: actions/upload-artifact@v7
      with:
        name: vim-package-for-signing
        path: ./package/artifacts/files

    - name: SignPath code signing
      if: needs.check-updates.outputs.signing == 'yes'
      id: signpath-code-signing
      uses: SignPath/github-action-submit-signing-request@v2.2
      with:
        api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
        organization-id: 47c0047c-0c1d-42b2-a16c-4ea6907dc813
        project-slug: vim-win32-installer
        signing-policy-slug: release-signing
        github-artifact-id: '${{ steps.upload-unsigned-zip.outputs.artifact-id }}'
        wait-for-completion: false  # true doesn't seem to work. Manual approval is required.

    - name: Save code signing info
      if: needs.check-updates.outputs.signing == 'yes'
      shell: bash
      run: |
        mkdir -p package/artifacts/info
        cp repo-info/* package/artifacts/info

        echo "${{ steps.signpath-code-signing.outputs.signing-request-id }}" \
          | tee package/artifacts/info/signing-request-id.txt
        echo "${{ steps.signpath-code-signing.outputs.signing-request-web-url }}" \
          | tee package/artifacts/info/signing-request-web-url.txt

    - name: Upload Artifact (signing info)
      if: needs.check-updates.outputs.signing == 'yes'
      uses: actions/upload-artifact@v7
      with:
        name: info
        path: ./package/artifacts/info

    - name: Trigger upload-signed-files
      if: needs.check-updates.outputs.signing == 'yes'
      shell: bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Trigger upload-signed-files.yml.
        # It is expected to fail due to waiting for approval.
        gh workflow run upload-signed-files.yml -f run_id=${{ github.run_id }} | tee log.txt
        grep '^https://' log.txt > upload-workflow-url.txt

    # TODO: Create an installer using with signed files, then upload to SignPath again.

    - name: Get changelog
      id: changelog
      run: |
        latesttag=$(cat repo-info/latesttag.txt)
        ver=${latesttag#v}
        echo "tag=${latesttag}" >> $GITHUB_OUTPUT
        cp repo-info/latesttag.txt vimver.txt

        URL=https://github.com/${{ github.repository }}/releases/download

        cat << EOF > release_notes.md
        [![${latesttag}](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/total.svg)](https://github.com/${{ github.repository }}/releases/tag/${latesttag})
        Nightly Vim Windows build snapshots ([more information](https://vim.fandom.com/wiki/Where_to_download_Vim)).

        **If you do not know what to use, use the 32bit installer (use the signed one, if available).**

        Signed releases will occasionally be provided on a best effort approach.
        ### Changes:

        $(cat repo-info/changelog.md)

        <!--
        _This release includes signed files_
        -->
        ### Files:
        <!--  commented out, because will only be enabled once the signed files are uploaded manually.
        #### :lock: Signed Files:
        * [![gvim_${ver}_x86_signed.exe](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x86_signed.exe.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x86_signed.exe)
          Signed 32-bit installer (*If you don't know what to use, use this one*)
        * [![gvim_${ver}_x64_signed.exe](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x64_signed.exe.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x64_signed.exe)
          Signed 64-bit installer
        * [![gvim_${ver}_arm64_signed.exe](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_arm64_signed.exe.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_arm64_signed.exe)
          Signed ARM64-bit installer
        * [![gvim_${ver}_x86_signed.zip](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x86_signed.zip.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x86_signed.zip)
          Signed 32-bit zip archive
        * [![gvim_${ver}_x64_signed.zip](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x64_signed.zip.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x64_signed.zip)
          Signed 64-bit zip archive
        * [![gvim_${ver}_arm64_signed.zip](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_arm64_signed.zip.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_arm64_signed.zip)
          Signed ARM64-bit zip archive
        -->
        #### :unlock: Unsigned Files:
        * [![gvim_${ver}_x86.exe](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x86.exe.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x86.exe)
          32-bit installer (*If you don't know what to use, use this one*)
        * [![gvim_${ver}_x64.exe](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x64.exe.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x64.exe)
          64-bit installer
        * [![gvim_${ver}_arm64.exe](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_arm64.exe.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_arm64.exe)
          ARM64-bit installer
        * [![gvim_${ver}_x86.zip](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x86.zip.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x86.zip)
          32-bit zip archive
        * [![gvim_${ver}_x64.zip](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x64.zip.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x64.zip)
          64-bit zip archive
        * [![gvim_${ver}_arm64.zip](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_arm64.zip.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_arm64.zip)
          ARM 64-bit zip archive
        * [![gvim_${ver}_x86_pdb.7z](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x86_pdb.7z.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x86_pdb.7z)
          pdb files for debugging the corresponding 32-bit executable
        * [![gvim_${ver}_x64_pdb.7z](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_x64_pdb.7z.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_x64_pdb.7z)
          pdb files for debugging the corresponding 64-bit executable
        * [![gvim_${ver}_arm64_pdb.7z](https://img.shields.io/github/downloads/${{ github.repository }}/${latesttag}/gvim_${ver}_arm64_pdb.7z.svg?label=downloads&logo=vim)](${URL}/${latesttag}/gvim_${ver}_arm64_pdb.7z)
          pdb files for debugging the corresponding ARM 64-bit executable

        <details>
        <summary>Interface Information</summary>

        * [Strawberry Perl](http://strawberryperl.com/) ${{ env.PERL_VER_DOT_64 }}
        <!-- * [ActiveTcl](http://www.activestate.com/activetcl/downloads) 8.6.6 -->
        * [LuaBinaries](http://luabinaries.sourceforge.net/download.html) ${{ env.LUA_VER_DOT }}
        * [Python2](https://www.python.org/downloads/) 2.7
        * [Python3](https://www.python.org/downloads/) 3.8 or later
        * [Racket](https://download.racket-lang.org/releases/${{ env.RACKET_RELEASE }}/) ${{ env.RACKET_RELEASE }} (BC)
        * [RubyInstaller](http://rubyinstaller.org/downloads/) ${{ env.RUBY_VER_DOT }}
        * [libsodium](https://download.libsodium.org/libsodium/) ${{ env.SODIUM_RELEASE }}
        </details>

        See the [README](https://github.com/vim/vim-win32-installer/blob/master/README.md) for detail.
        EOF

    - name: Commit and push
      id: commit
      run: |
        if [ "${{github.event_name}}" = 'workflow_dispatch' ] && [ "${{inputs.base_commit}}" != 'master' ]; then
          git switch -c "work-${{inputs.tag}}"
        fi
        if git diff --quiet HEAD vimver.txt; then
          echo ${COL_YELLOW}No updates.${COL_RESET}
          exit 1  # This should not happen.
        fi
        cp repo-info/latestrev.txt vimrev.txt
        git config --local user.name "$USER_NAME"
        git config --local user.email "$USER_EMAIL"
        git commit -a \
          -m "Update Vim to ${{ steps.changelog.outputs.tag }}" \
          -m "$(head -n 50 repo-info/changelog.txt)"
        git tag "${{ steps.changelog.outputs.tag }}"
        git push origin HEAD --tags

    - name: Create Release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        name: ${{ steps.changelog.outputs.tag }}
        body_path: release_notes.md
        draft: false
        prerelease: false
        #token: ${{ steps.app-token.outputs.token }}
        files: |
          ./vim-package-x86/gvim_*.exe
          ./vim-package-x86/gvim_*.zip
          ./vim-package-x86/gvim_*_pdb.7z
          ./vim-package-x64/gvim_*.exe
          ./vim-package-x64/gvim_*.zip
          ./vim-package-x64/gvim_*_pdb.7z
          ./vim-package-arm64/gvim_*.exe
          ./vim-package-arm64/gvim_*.zip
          ./vim-package-arm64/gvim_*_pdb.7z

    - name: Post Summary
      run: |
        TAG=${{ steps.changelog.outputs.tag }}

        cat << EOF >> $GITHUB_STEP_SUMMARY
        ## ✅ Windows Build Summary

        **Tag:** \`${TAG}\`
        **Repository:** \`${{ github.repository }}\`
        **Artifacts Uploaded:**
        - 🟩 [x86/x64/arm64 packages](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

        **Release Status:**
        - 🆕 Created a new release: [\`${TAG}\`](https://github.com/${{ github.repository }}/releases/tag/${TAG})
        - 📦 Uploaded artifacts to the release via \`softprops/action-gh-release\`

        **Security Provenance:**
        - 🔒 Attested x86/x64/arm64 packages using [actions/attest](https://github.com/actions/attest)

        **(For admin) Code signing submitted:**
        - 🟩 x86/x64/arm64 packages: [$(cat package/artifacts/info/signing-request-id.txt)]($(cat package/artifacts/info/signing-request-web-url.txt))

        **(For admin) Upload signed files:**
        The following workflow has been triggered to upload the signed files:
        <$(cat upload-workflow-url.txt)>
        It is expected to fail due to waiting for approval. Rerun it after approval of SignPath code signing.

        Or, trigger a new workflow by running the following command after approval:
        \`\`\`
        gh workflow run upload-signed-files.yml -f run_id=${{ github.run_id }}
        \`\`\`
        To trigger it from a browser, go to the [Upload signed files](https://github.com/vim/vim-win32-installer/actions/workflows/upload-signed-files.yml) workflow page and run it manually by setting \`run_id\` to \`${{ github.run_id }}\`.
        EOF

# vim: ts=2 sw=2 sts=2 et
