name: Upload signed files

# This workflow should be executed manually after a release has been created
# and SignPath code signing has been approved.
# run_id for the corresponding release must be specified.

on:
  #push:
  #  branches:
  #    - 'upload-signed-files' # XXX: for debugging
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Actions run_id when created the corresponding release'
        required: true
        type: string

permissions:
  id-token: write # needed for attestation
  attestations: write
  contents: write # to update a release

jobs:
  upload-signed-files:
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v7

      - name: Download build info
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = 'workflow_dispatch' ]; then
            RUN_ID=${{ inputs.run_id }}
          #else
          #  # XXX: For debugging
          #  RUN_ID=26345580501
          fi

          gh run download "${RUN_ID}" --name "info" --dir info

      - name: Check if signed files have been uploaded
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_FILE_COUNT: 6
        run: |
          TAG=$(cat info/latesttag.txt)
          gh release view "${TAG}" --json assets \
            --jq '.assets[].url | select(test("_signed\\.(exe|zip)"))' | \
            tee signed_files.txt
          if [ "$(wc -l < signed_files.txt)" -eq "${UPLOAD_FILE_COUNT}" ]; then
            echo "Signed files have already been uploaded."
            exit 1
          fi

      - name: Download signed files
        shell: bash
        timeout-minutes: 10
        env:
          SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
          ORGANIZATION_ID: 47c0047c-0c1d-42b2-a16c-4ea6907dc813
        run: |
          SIGNING_REQUEST_ID=$(cat info/signing-request-id.txt)
          REQUEST_URL=https://app.signpath.io/API/v1/${ORGANIZATION_ID}/SigningRequests/${SIGNING_REQUEST_ID}

          # Check SignPath status
          status=InProgress
          while [ "$status" = "InProgress" ]; do
            status=$(curl -f --silent -H "Authorization: Bearer ${SIGNPATH_API_TOKEN}" ${REQUEST_URL} \
              | jq -r .status)

            echo "SignPath status: $status"
            case "$status" in
              WaitingForApproval)
                echo "Not approved yet. Approve it first:"
                cat info/signing-request-web-url.txt
                exit 1
                ;;
              InProgress)
                ;;
              Completed)
                break
                ;;
              *)
                exit 1
                ;;
            esac

            sleep 10
          done

          # Download the signed files
          curl -f -H "Authorization: Bearer ${SIGNPATH_API_TOKEN}" \
               -o package.zip \
               ${REQUEST_URL}/SignedArtifact
          unzip package.zip -d package

          rm -f package/*_pdb.*

          # rename to *_signed.*
          for i in package/gvim_*; do
            n=$(echo "$i" | sed -e 's/\(gvim_.*\)\.\(exe\|zip\)/\1_signed.\2/')
            mv "$i" "$n"
          done

          ls -l package

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: signed-package
          path: |
            ./package/gvim_*_signed.*

      - name: Attest
        uses: actions/attest@v4.1.1
        with:
          subject-path: ./package/gvim_*_signed.*

      - name: Update release
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(cat info/latesttag.txt)

          # Original release notes
          echo '---------------'
          gh release view "${TAG}" --json body --jq '.body' | tee body.md
          echo '---------------'

          # Remove comments
          sed -i -e '/^<!--$/d' -e '/^-->/d' -e '/^<!--  *commented out,/d' body.md

          # Updated release notes
          echo '---------------'
          cat body.md
          echo '---------------'

          # Upload the signed files
          for i in package/gvim_*_signed.*; do
            gh release upload "${TAG}" "$i" --clobber
          done
          # Update the release notes
          gh release edit "${TAG}" -F body.md

      - name: Post Summary
        run: |
          TAG=$(cat info/latesttag.txt)

          cat << EOF >> $GITHUB_STEP_SUMMARY
          ## ✅ Windows Build Summary

          **Tag:** \`${TAG}\`
          **Repository:** \`${{ github.repository }}\`
          **Artifacts Uploaded:**
          - 🟩 [signed x86/x64/arm64 packages](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

          **Release Status:**
          - ✨ Updated the release: [\`${TAG}\`](https://github.com/${{ github.repository }}/releases/tag/${TAG})
          - 📦 Uploaded artifacts to the release via \`gh release upload\`

          **Security Provenance:**
          - 🔒 Attested signed x86/x64/arm64 packages using [actions/attest](https://github.com/actions/attest)
          EOF

# vim: ts=2 sw=2 sts=2 et
